apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - audit-consumer/deployment.yaml
  - ai-consumer/deployment.yaml
  - metrics-consumer/deployment.yaml
  - notifier-service/deployment.yaml
  - search-indexer/deployment.yaml
